<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mst_nav_user_model extends CI_Model
{

    public $table = 'mst_nav_user';
		
    public $id = 'login_name';    
		public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        #$this->db->order_by($this->id, $this->order);
        #return $this->db->get($this->table)->result();
				
				$sql = "SELECT * FROM ".$this->table." ORDER BY ".$this->id." ".$this->order."";
				$query = $this->db->query($sql);
				$result = $query->result();
				return $result;
    }

    // get data by id
    function get_by_id($id)
    {
        #$this->db->where($this->id, $id);
        #return $this->db->get($this->table)->row();
				
				$sql = "SELECT 	* 
								FROM 		".$this->table." 
								WHERE		".$this->id."='".$id."'
								ORDER BY ".$this->id." ".$this->order."";
				$query = $this->db->query($sql);
				$result = $query->result();
				$result = $result[0];
				return $result;
    }
    
    // get total rows
    function total_rows($q = NULL) 
		{
			$sql = "SELECT 	* 
								FROM 		".$this->table."
								";
				if($q!=NULL)
				{
					$sql .= " WHERE FALSE ";
					$sql .= "OR LOWER(aktif) LIKE LOWER('%".$q."%') ";
						$sql .= "OR LOWER(created) LIKE LOWER('%".$q."%') ";
						$sql .= "OR LOWER(creator) LIKE LOWER('%".$q."%') ";
						$sql .= "OR LOWER(id_dokter) LIKE LOWER('%".$q."%') ";
						$sql .= "OR LOWER(id_role) LIKE LOWER('%".$q."%') ";
						$sql .= "OR LOWER(login_pass) LIKE LOWER('%".$q."%') ";
						$sql .= "OR LOWER(name) LIKE LOWER('%".$q."%') ";
						$sql .= "OR LOWER(updated) LIKE LOWER('%".$q."%') ";
						$sql .= "OR LOWER(updater) LIKE LOWER('%".$q."%') ";
						}
				$sql = "SELECT COUNT(*) as total_rows FROM (".$sql.") abc";
				$query = $this->db->query($sql);
				$result = $query->result();
				$total_rows = $result[0]->total_rows;
				return $total_rows;
	}
	
    // get data with limit and search
    function get_limit_data($limit=NULL, $start = 0, $q = NULL) {
        #$this->db->order_by($this->id, $this->order);
        $sql = "SELECT 	a.*,b.nama AS nama_role
				FROM 	".$this->table." a
						LEFT JOIN mst_nav_role b ON (a.id_role=b.id_role)
				";
				if($q!=NULL)
				{
					$sql .= "WHERE FALSE ";
					$sql .= "OR LOWER(b.nama) LIKE LOWER('%".$q."%') ";
					$sql .= "OR LOWER(a.name) LIKE LOWER('%".$q."%') ";
					$sql .= "  ";
					}
				$sql .= " ORDER BY a.name LIMIT ".$start.",".$limit."";
				$query = $this->db->query($sql);
				$result = $query->result();
				return $result;
	}
	
    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file mst_nav_user_model.php */
/* Location: ./application/models/mst_nav_user_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-13 10:01:00 */
/* http://harviacode.com */