<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mst_nav_submenu_model extends CI_Model
{

    public $table = 'mst_nav_submenu';
		
    public $id = 'id_submenu';    
		public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        #$this->db->order_by($this->id, $this->order);
        #return $this->db->get($this->table)->result();
				
				$sql = "SELECT * FROM ".$this->table." ORDER BY ".$this->id." ".$this->order."";
				$query = $this->db->query($sql);
				$result = $query->result();
				return $result;
    }

    // get data by id
    function get_by_id($id)
    {
        #$this->db->where($this->id, $id);
        #return $this->db->get($this->table)->row();
				
				$sql = "SELECT 	* 
								FROM 		".$this->table." 
								WHERE		".$this->id."='".$id."'
								ORDER BY ".$this->id." ".$this->order."";
				$query = $this->db->query($sql);
				$result = $query->result();
				$result = $result[0];
				return $result;
    }
    
    // get total rows
    function total_rows($q = NULL) 
		{
			$sql = "SELECT 	* 
								FROM 		".$this->table."
								";
				if($q!=NULL)
				{
					$sql .= " WHERE FALSE ";
					$sql .= "OR LOWER(aktif) LIKE LOWER('%".$q."%') ";
						$sql .= "OR LOWER(icon) LIKE LOWER('%".$q."%') ";
						$sql .= "OR LOWER(id_menu) LIKE LOWER('%".$q."%') ";
						$sql .= "OR LOWER(no_urut) LIKE LOWER('%".$q."%') ";
						$sql .= "OR LOWER(submenu) LIKE LOWER('%".$q."%') ";
						$sql .= "OR LOWER(url) LIKE LOWER('%".$q."%') ";
						}
				$sql = "SELECT COUNT(*) as total_rows FROM (".$sql.") abc";
				$query = $this->db->query($sql);
				$result = $query->result();
				$total_rows = $result[0]->total_rows;
				return $total_rows;
	}
	
    // get data with limit and search
    function get_limit_data($limit=NULL, $start = 0, $q = NULL) {
        #$this->db->order_by($this->id, $this->order);
        $sql = "SELECT 	(CASE WHEN b.`is_grup_submenu`=0 THEN b.menu ELSE NULL END) AS menu_utama
						,(CASE WHEN b.`is_grup_submenu`=1 THEN b.menu ELSE NULL END) AS menu_grup_submenu
						,(CASE WHEN b.`is_grup_submenu`=0 THEN b.urutan 
							ELSE CONCAT((SELECT x.urutan FROM mst_nav_menu x WHERE x.id_menu=b.id_menu_parent),'.',COALESCE(b.`urutan`,0),'.',COALESCE(a.`no_urut`,0)) 
						  END) AS urutan_ulang
						,a.aktif,a.`submenu`,a.`id_submenu`,a.url
				FROM	mst_nav_menu b
						LEFT JOIN mst_nav_submenu a ON (a.`id_menu`=b.`id_menu`)
								";
				if($q!=NULL)
				{
					$sql .= " WHERE FALSE ";
					$sql .= "OR LOWER(a.submenu) LIKE LOWER('%".$q."%') ";
					$sql .= "OR LOWER(a.url) LIKE LOWER('%".$q."%') ";
					}
				$sql .= " 
						ORDER BY (CASE WHEN b.`is_grup_submenu`=0 THEN b.urutan 
							ELSE CONCAT((SELECT x.urutan FROM mst_nav_menu x WHERE x.id_menu=b.id_menu_parent),'.',COALESCE(b.`urutan`,0),'.',COALESCE(a.`no_urut`,0)) 
						  END) 
						LIMIT ".$start.",".$limit."";
							
				#echo "<pre>".$sql."</pre>";
				$query = $this->db->query($sql);
				$result = $query->result();
				return $result;
	}
	
    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file mst_nav_submenu_model.php */
/* Location: ./application/models/mst_nav_submenu_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-13 09:17:19 */
/* http://harviacode.com */